# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  # Handle [skip ci] / [ci skip] directives in commit messages
  init:
    name: init
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
    steps:
      - name: Checkuout
        uses: actions/checkout@v3

      - id: ci-skip-step
        uses: mstachniuk/ci-skip@v1

  # Fast unit tests flow
  test_push:
    needs: init
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkuout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install
        run: npm i

      - name: Run tests
        run: npm run test


  # Full tests for PR
  test_pr:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        node-version: [ 12, 14, 16 ]

    name: Test (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: init

    steps:
      - name: Checkuout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm i

      - name: Run tests
        run: npm run test

  release:
    name: Release
    # https://github.community/t/trigger-job-on-tag-push-only/18076
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: test_push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install
        run: npm i

      - name: Compile
        run: npm run build

      - name: Create .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_USER: 'qiwibot'
          GIT_COMMITTER_NAME: 'qiwibot'
          GIT_COMMITTER_EMAIL: 'opensource@qiwi.com'
        run: npm_config_yes=true npx zx-semrel
